# Generated by Django 2.2 on 2019-05-06 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='adding_date',
        ),
    ]
