# Generated by Django 2.2 on 2019-05-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_project_adding_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='last_modified',
        ),
        migrations.AddField(
            model_name='project',
            name='body',
            field=models.TextField(blank=True, verbose_name='script body'),
        ),
    ]
